-- SCRIPT TO CREATE tablespaces for schema and the schema owner&users
-- *** Directory Layout - Examples ***
-- ${ORACLE_BASE}/oradata/${ORACLE_SID}/app01
-- UNIX = /u01/oradata/ZDBT01L/app01/app01_tblsp.dbf
-- Windows = E:\app\oracle\oradata\ZDBT01W\app01
CREATE TABLESPACE APP01
DATAFILE '/u01/oradata/ZDBT01L/app01/app01_tblsp.dbf' SIZE 5M REUSE 
AUTOEXTEND ON NEXT 300 K MAXSIZE UNLIMITED
ONLINE;

commit;

CREATE USER appdba IDENTIFIED BY "appdba"
DEFAULT TABLESPACE APP01 TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON APP01 
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO appdba;
GRANT CREATE TABLE TO appdba;
GRANT CREATE VIEW TO appdba;
GRANT CREATE TRIGGER TO appdba;
GRANT CREATE PROCEDURE TO appdba;
GRANT CREATE PUBLIC SYNONYM TO appdba; 
GRANT DROP PUBLIC SYNONYM TO appdba; 

commit;

CREATE USER reporter IDENTIFIED BY "reporter" 
DEFAULT TABLESPACE APP01 TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON APP01 
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO reporter;

commit;

quit;
