-- ZDBT01W_destroy.sql
DROP TABLE STUDENT;
DROP TABLE GRADE_REPORT;
DROP TABLE CLSECTION;
DROP TABLE DEPARTMENT_TO_MAJOR;
DROP TABLE PREREQ;
DROP TABLE COURSE;
DROP TABLE CAP;
DROP TABLE ROOM;
DROP TABLE DEPENDENT;
DROP TABLE PLANTS;

commit;
quit;